<a href="https://colab.research.google.com/github/9-coding/DataScience/blob/main/Iris_DecisionTreeClassifier_BaggingClassifier_VotingClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
'''
Using bagging method with a decision tree algorithm, 
predict with voting method and calculate the accuracy using confusion matrix. 
Datasets 10 iris-bagging datasets (for training 10 classifiers), each with 30 records 1 test dataset with 150 records 
Attributes: sepal length, sepal width, petal length, petal width 
Generate a decision tree classifier model using the sklearn DecisionTreeClassifier function 
Run 10 (training) bagging rounds with BaggingClassifier function. 
Using the test dataset, predict the labels using voting. 
Calculate the accuracy using confusion matrix.
'''

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings(action='ignore')
from sklearn.datasets import load_iris
iris = load_iris()
from sklearn.model_selection import train_test_split
from sklearn.ensemble import BaggingClassifier, VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Load the iris dataset
iris = load_iris()
X = iris.data
y = iris.target

iris_data = iris.data
iris_label = iris.target

df = pd.DataFrame(data = iris_data, columns = iris.feature_names)
df['label'] = iris.target
df.head()

X_train, X_test, y_train, y_test = train_test_split(X, y)

# generate a decision tree classifier model
tree_classifier = DecisionTreeClassifier()
bagging_classifier = BaggingClassifier(tree_classifier, n_estimators=10)
bagging_classifier.fit(X_train, y_train)

# predict
voting = VotingClassifier(estimators=[('bg', bagging_classifier)])
voting.fit(X_train, y_train)
y_pred = voting.predict(X_test)

# calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Calculate confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)


Accuracy: 0.9736842105263158
Confusion Matrix:
[[14  0  0]
 [ 0 13  0]
 [ 0  1 10]]
